### ISSUE TITLE
External table definitions are not exported

### ISSUE THREAD

**Issue by cronologi** [microsoft/synckusto#10]
Hello,

thank you for the tool! It really helps me out. However, I do not see external table definitions exported into csl files. Is this feature missing from the tool, or?

Thanks,
Davor

**Comment by benmartens** [comment]
Sorry for the slow reply. You are correct that external table definitions are not exported, and no we don't plan to add this. The Delta-Kusto project might help you out. I know it does things like policies and stuff in addition to the basic tables and functions that SyncKusto does so maybe it would include external tables too.
