### ISSUE TITLE
.kql instead of .csl?

### ISSUE THREAD

**Issue by jruales** [microsoft/synckusto#12]
The .csl extension is a vestige of the time when Kusto was called Cousteau. Should Sync Kusto move to using the .kql extension instead?

**Comment by jruales** [comment]
It's also worth noting that when downloading a query from Azure Data Explorer, it's downloaded with the .kql extension.

**Comment by anladwig** [comment]
#21

**Comment by benmartens** [comment]
This is now in build 20220611
