### ISSUE TITLE
Settings screen hangs when inputting settings

### ISSUE THREAD

**Issue by RussOBrienSea** [microsoft/synckusto#25]
The settings screen appears to hang when initially populating the temporary database cluster and database details.

symptoms are that the screen is not dismissed and the mouse pointer stay on hourglass mode and the app becomes unresponsive.  

Eventually it needs closing via task manager.

**Comment by benmartens** [comment]
Apologies for the very delayed response (I need to adjust my notification settings.) Is this still happening?

**Comment by benmartens** [comment]
Closing as not repro. Please reopen with more details if this is still happening.
