### ISSUE TITLE
BCDR - accidental data deletion

### ISSUE THREAD

**Issue by msjammu** [microsoft/synckusto#4]
I ended up specifying my source database as temporary database as well without realizing the results. The tool cleanup up my source database without warnings. Now need to do some BCDR. Please add a warning when this happens or switch to another temporary database.
![kustosync](https://user-images.githubusercontent.com/2992509/74282535-2aead700-4cd5-11ea-9f35-e000e5ceb21c.PNG)

**Comment by benmartens** [comment]
I just submitted a change to this form that adds more text in red explaining that the user is specifying a temporary database where everything is deleted.

**Comment by msjammu** [comment]
While coloring red would give additional clues to some users, it would not be accessible. I think what really would help is a check which halts Update operation at the onset if the source database/cluster is same as temporary database/cluster.. giving a warning to the user.
